spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
    defer-datasource-initialization: true

# Actuator Configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always

# Logging for Production
logging:
  level:
    com.adotransfer: DEBUG
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.boot: INFO
    org.springframework.context: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"