spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ado_transfer}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true

# Logging for Debug
logging:
  level:
    com.adotransfer: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.context: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
